### ISSUE TITLE
There are no commands defined in the "lang" namespace.

### ISSUE THREAD

**Issue by topclaudy** [rmariuzzo/Laravel-JS-Localization#75] opened 2016-12-06 22:05 UTC
Running "php artisan lang:js" after installation results in "There are no commands defined in the "lang" namespace." in Laravel 5.3

**Comment by rmariuzzo** [comment] 2016-12-06 22:11
Hey @topclaudy! Did you add this service provider: `Mariuzzo\LaravelJsLocalization\LaravelJsLocalizationServiceProvider::class` in your `app/config.php` file?

**Comment by topclaudy** [comment] 2016-12-06 22:13
@rmariuzzo Yes I added it after installation.

**Comment by rmariuzzo** [comment] 2016-12-06 22:31
That's weird, try running: `php artisan clear-compiled` and rerun the command. If it fails, please give details of you Laravel installation (version, os).

**Comment by topclaudy** [comment] 2016-12-06 22:49
The issue persists after running `php artisan clear-compiled`. I'm running Laravel 5.3.26 on macOS Sierra. I also noticed that the command `php artisan vendor:publish --provider="Mariuzzo\LaravelJsLocalization\LaravelJsLocalizationServiceProvider"` doesn't publish any configuration file (Nothing to publish for tag []).

**Comment by rmariuzzo** [comment] 2017-01-07 20:05
Hey @topclaudy! Sorry for the long delay. Did you solved this?

**Comment by tenaciousd93** [comment] 2017-01-18 09:53
Same problem here! `Laraval 5.3` with  `mariuzzo/laravel-js-localization` v1.3.

To solve `php artisan clear-compiled` fail I ran `composer remove mariuzzo/laravel-js-localization`, and went to `bootstrap/cache/config.php` and removed the line `Mariuzzo\LaravelJsLocalization\LaravelJsLocalizationServiceProvider` in **providers** array.

Clean all with `composer clear` and `php artisan clear-compiled`.

In my other project with `Laravel 5.1` and `mariuzzo/laravel-js-localization` v1.2.* works good.

**Comment by rmariuzzo** [comment] 2017-02-24 17:19
I will close this one for now, because I couldn't reproduce this issue. If it happens again, I will open it including more details.

**Closed by rmariuzzo** 2017-02-24 17:19 UTC
Labels: help wanted, open
