### ISSUE TITLE
Uncaught TypeError: Lang.setMessages is not a function

### ISSUE THREAD

**Issue by ksdev-pl** [rmariuzzo/Laravel-JS-Localization#57] opened 2016-08-27 15:41 UTC
Hi

I've installed the v.1.3.0 in the Laravel 5.3, generated the lang file:
```
php artisan lang:js public/js/lang.js
```
added the file to my template:
```
...
<script src="{{ url('/js/lang.js') }}"></script>
<script src="{{ url('/js/webapp.js') }}"></script>

</body>
</html>
```
and I'm getting an error in the Chrome 52 console:
```
Uncaught TypeError: Lang.setMessages is not a function (lang.js:9)
```
This is my lang.js file:
```js
/*!
 *  Lang.js for Laravel localization in JavaScript.
 *
 *  @version 1.1.0
 *  @license MIT
 *  @site    https://github.com/rmariuzzo/Lang.js
 *  @author  Rubens Mariuzzo <rubens@mariuzzo.com>
 */
(function(root,factory){"use strict";if(typeof define==="function"&&define.amd){define([],factory())}else if(typeof exports==="object"){module.exports=factory()}else{root.Lang=factory()}})(this,function(){"use strict";var defaults={locale:"en"};var Lang=function(options){this.locale=options.locale||defaults.locale;this.fallback=options.fallback;this.messages=options.messages};Lang.prototype.setMessages=function(messages){this.messages=messages};Lang.prototype.getLocale=function(){return this.locale||options.defaultLocale};Lang.prototype.setLocale=function(locale){this.locale=locale};Lang.prototype.getFallback=function(){return this.fallback};Lang.prototype.setFallback=function(fallback){this.fallback=fallback};Lang.prototype.has=function(key,locale){if(typeof key!=="string"||!this.messages){return false}return this._getMessage(key,locale)!==null};Lang.prototype.get=function(key,replacements,locale){if(!this.has(key)){return key}var message=this._getMessage(key,locale);if(message===null){return key}if(replacements){message=this._applyReplacements(message,replacements)}return message};Lang.prototype.trans=function(key,replacements){return this.get(key,replacements)};Lang.prototype.choice=function(key,number,replacements,locale){replacements=typeof replacements!=="undefined"?replacements:{};replacements.count=number;var message=this.get(key,replacements,locale);if(message===null||message===undefined){return message}var messageParts=message.split("|");var explicitRules=[];var regex=/{\d+}\s(.+)|\[\d+,\d+\]\s(.+)|\[\d+,Inf\]\s(.+)/;for(var i=0;i<messageParts.length;i++){messageParts[i]=messageParts[i].trim();if(regex.test(messageParts[i])){var messageSpaceSplit=messageParts[i].split(/\s/);explicitRules.push(messageSpaceSplit.shift());messageParts[i]=messageSpaceSplit.join(" ")}}if(messageParts.length===1){return message}for(var j=0;j<explicitRules.length;j++){if(this._testInterval(number,explicitRules[j])){return messageParts[j]}}var pluralForm=this._getPluralForm(number);return messageParts[pluralForm]};Lang.prototype.transChoice=function(key,count,replacements){return this.choice(key,count,replacements)};Lang.prototype._parseKey=function(key,locale){if(typeof key!=="string"||typeof locale!=="string"){return null}var segments=key.split(".");return{source:locale+"."+segments[0].replace("/","."),sourceFallback:this.getFallback()+"."+segments[0].replace("/","."),entries:segments.slice(1)}};Lang.prototype._getMessage=function(key,locale){locale=locale||this.getLocale();key=this._parseKey(key,locale);if(this.messages[key.source]===undefined&&this.messages[key.sourceFallback]===undefined){return null}var message=this.messages[key.source]||this.messages[key.sourceFallback];while(key.entries.length&&(message=message[key.entries.shift()]));if(typeof message!=="string"){return null}return message};Lang.prototype._applyReplacements=function(message,replacements){for(var replace in replacements){message=message.split(":"+replace).join(replacements[replace])}return message};Lang.prototype._testInterval=function(count,interval){return false};Lang.prototype._getPluralForm=function(count){switch(this.locale){case"az":case"bo":case"dz":case"id":case"ja":case"jv":case"ka":case"km":case"kn":case"ko":case"ms":case"th":case"tr":case"vi":case"zh":return 0;case"af":case"bn":case"bg":case"ca":case"da":case"de":case"el":case"en":case"eo":case"es":case"et":case"eu":case"fa":case"fi":case"fo":case"fur":case"fy":case"gl":case"gu":case"ha":case"he":case"hu":case"is":case"it":case"ku":case"lb":case"ml":case"mn":case"mr":case"nah":case"nb":case"ne":case"nl":case"nn":case"no":case"om":case"or":case"pa":case"pap":case"ps":case"pt":case"so":case"sq":case"sv":case"sw":case"ta":case"te":case"tk":case"ur":case"zu":return count==1?0:1;case"am":case"bh":case"fil":case"fr":case"gun":case"hi":case"hy":case"ln":case"mg":case"nso":case"xbr":case"ti":case"wa":return count==0||count==1?0:1;case"be":case"bs":case"hr":case"ru":case"sr":case"uk":return count%10==1&&count%100!=11?0:count%10>=2&&count%10<=4&&(count%100<10||count%100>=20)?1:2;case"cs":case"sk":return count==1?0:count>=2&&count<=4?1:2;case"ga":return count==1?0:count==2?1:2;case"lt":return count%10==1&&count%100!=11?0:count%10>=2&&(count%100<10||count%100>=20)?1:2;case"sl":return count%100==1?0:count%100==2?1:count%100==3||count%100==4?2:3;case"mk":return count%10==1?0:1;case"mt":return count==1?0:count==0||count%100>1&&count%100<11?1:count%100>10&&count%100<20?2:3;case"lv":return count==0?0:count%10==1&&count%100!=11?1:2;case"pl":return count==1?0:count%10>=2&&count%10<=4&&(count%100<12||count%100>14)?1:2;case"cy":return count==1?0:count==2?1:count==8||count==11?2:3;case"ro":return count==1?0:count==0||count%100>0&&count%100<20?1:2;case"ar":return count==0?0:count==1?1:count==2?2:count%100>=3&&count%100<=10?3:count%100>=11&&count%100<=99?4:5;default:return 0}};return Lang});

(function () {
    Lang.setMessages({"en.validation":{"accepted":"The :attribute must be accepted.","active_url":"The :attribute is not a valid URL.","after":"The :attribute must be a date after :date.","alpha":"The :attribute may only contain letters.","alpha_dash":"The :attribute may only contain letters, numbers, and dashes.","alpha_num":"The :attribute may only contain letters and numbers.","array":"The :attribute must be an array.","before":"The :attribute must be a date before :date.","between":{"numeric":"The :attribute must be between :min and :max.","file":"The :attribute must be between :min and :max kilobytes.","string":"The :attribute must be between :min and :max characters.","array":"The :attribute must have between :min and :max items."},"boolean":"The :attribute field must be true or false.","confirmed":"The :attribute confirmation does not match.","date":"The :attribute is not a valid date.","date_format":"The :attribute does not match the format :format.","different":"The :attribute and :other must be different.","digits":"The :attribute must be :digits digits.","digits_between":"The :attribute must be between :min and :max digits.","dimensions":"The :attribute has invalid image dimensions.","distinct":"The :attribute field has a duplicate value.","email":"The :attribute must be a valid email address.","exists":"The selected :attribute is invalid.","file":"The :attribute must be a file.","filled":"The :attribute field is required.","image":"The :attribute must be an image.","in":"The selected :attribute is invalid.","in_array":"The :attribute field does not exist in :other.","integer":"The :attribute must be an integer.","ip":"The :attribute must be a valid IP address.","json":"The :attribute must be a valid JSON string.","max":{"numeric":"The :attribute may not be greater than :max.","file":"The :attribute may not be greater than :max kilobytes.","string":"The :attribute may not be greater than :max characters.","array":"The :attribute may not have more than :max items."},"mimes":"The :attribute must be a file of type: :values.","min":{"numeric":"The :attribute must be at least :min.","file":"The :attribute must be at least :min kilobytes.","string":"The :attribute must be at least :min characters.","array":"The :attribute must have at least :min items."},"not_in":"The selected :attribute is invalid.","numeric":"The :attribute must be a number.","present":"The :attribute field must be present.","regex":"The :attribute format is invalid.","required":"The :attribute field is required.","required_if":"The :attribute field is required when :other is :value.","required_unless":"The :attribute field is required unless :other is in :values.","required_with":"The :attribute field is required when :values is present.","required_with_all":"The :attribute field is required when :values is present.","required_without":"The :attribute field is required when :values is not present.","required_without_all":"The :attribute field is required when none of :values are present.","same":"The :attribute and :other must match.","size":{"numeric":"The :attribute must be :size.","file":"The :attribute must be :size kilobytes.","string":"The :attribute must be :size characters.","array":"The :attribute must contain :size items."},"string":"The :attribute must be a string.","timezone":"The :attribute must be a valid zone.","unique":"The :attribute has already been taken.","url":"The :attribute format is invalid.","custom":{"attribute-name":{"rule-name":"custom-message"}},"attributes":[]},"en.passwords":{"password":"Passwords must be at least six characters and match the confirmation.","reset":"Your password has been reset!","sent":"We have e-mailed your password reset link!","token":"This password reset token is invalid.","user":"We can't find a user with that e-mail address."},"en.auth":{"failed":"These credentials do not match our records.","throttle":"Too many login attempts. Please try again in :seconds seconds."},"en.pagination":{"previous":"&laquo; Previous","next":"Next &raquo;"}});
})();
```
I cannot find the reason of the console error. Do you know what it is?

Thanks for your work.

**Comment by rmariuzzo** [comment] 2016-08-27 15:50
Thanks, I will check right away.

On Aug 27, 2016 11:41 AM, "KS" <notifications@github.com> wrote:

Hi

I've installed the v.1.3.0 in the Laravel 5.3, generated the lang file:

php artisan lang:js public/js/lang.js

added the file to my template:

...
<script src="{{ url('/js/lang.js') }}"></script>
<script src="{{ url('/js/webapp.js') }}"></script>

</body>
</html>

and I'm getting an error in the Chrome 52 console:

Uncaught TypeError: Lang.setMessages is not a function (lang.js:9)

This is my lang.js file:

/*! *  Lang.js for Laravel localization in JavaScript. * *  @version
1.1.0 *  @license MIT *  @site    https://github.com/rmariuzzo/Lang.js
*  @author  Rubens Mariuzzo <rubens@mariuzzo.com> */
(function(root,factory){"use strict";if(typeof
define==="function"&&define.amd){define([],factory())}else if(typeof
exports==="object"){module.exports=factory()}else{root.Lang=factory()}})(this,function(){"use
strict";var defaults={locale:"en"};var
Lang=function(options){this.locale=options.locale||defaults.locale;this.fallback=options.fallback;this.messages=options.messages};Lang.prototype.setMessages=function(messages){this.messages=messages};Lang.prototype.getLocale=function(){return
this.locale||options.defaultLocale};Lang.prototype.setLocale=function(locale){this.locale=locale};Lang.prototype.getFallback=function(){return
this.fallback};Lang.prototype.setFallback=function(fallback){this.fallback=fallback};Lang.prototype.has=function(key,locale){if(typeof
key!=="string"||!this.messages){return false}return
this._getMessage(key,locale)!==null};Lang.prototype.get=function(key,replacements,locale){if(!this.has(key)){return
key}var message=this._getMessage(key,locale);if(message===null){return
key}if(replacements){message=this._applyReplacements(message,replacements)}return
message};Lang.prototype.trans=function(key,replacements){return
this.get(key,replacements)};Lang.prototype.choice=function(key,number,replacements,locale){replacements=typeof
replacements!=="undefined"?replacements:{};replacements.count=number;var
message=this.get(key,replacements,locale);if(message===null||message===undefined){return
message}var messageParts=message.split("|");var explicitRules=[];var
regex=/{\d+}\s(.+)|\[\d+,\d+\]\s(.+)|\[\d+,Inf\]\s(.+)/;for(var
i=0;i<messageParts.length;i++){messageParts[i]=messageParts[i].trim();if(regex.test(messageParts[i])){var
messageSpaceSplit=messageParts[i].split(/\s/);explicitRules.push(messageSpaceSplit.shift());messageParts[i]=messageSpaceSplit.join("
")}}if(messageParts.length===1){return message}for(var
j=0;j<explicitRules.length;j++){if(this._testInterval(number,explicitRules[j])){return
messageParts[j]}}var pluralForm=this._getPluralForm(number);return
messageParts[pluralForm]};Lang.prototype.transChoice=function(key,count,replacements){return
this.choice(key,count,replacements)};Lang.prototype._parseKey=function(key,locale){if(typeof
key!=="string"||typeof locale!=="string"){return null}var
segments=key.split(".");return{source:locale+"."+segments[0].replace("/","."),sourceFallback:this.getFallback()+"."+segments[0].replace("/","."),entries:segments.slice(1)}};Lang.prototype._getMessage=function(key,locale){locale=locale||this.getLocale();key=this._parseKey(key,locale);if(this.messages[key.source]===undefined&&this.messages[key.sourceFallback]===undefined){return
null}var message=this.messages[key.source]||this.messages[key.sourceFallback];while(key.entries.length&&(message=message[key.entries.shift()]));if(typeof
message!=="string"){return null}return
message};Lang.prototype._applyReplacements=function(message,replacements){for(var
replace in replacements){message=message.split(":"+replace).join(replacements[replace])}return
message};Lang.prototype._testInterval=function(count,interval){return
false};Lang.prototype._getPluralForm=function(count){switch(this.locale){case"az":case"bo":case"dz":case"id":case"ja":case"jv":case"ka":case"km":case"kn":case"ko":case"ms":case"th":case"tr":case"vi":case"zh":return
0;case"af":case"bn":case"bg":case"ca":case"da":case"de":case"el":case"en":case"eo":case"es":case"et":case"eu":case"fa":case"fi":case"fo":case"fur":case"fy":case"gl":case"gu":case"ha":case"he":case"hu":case"is":case"it":case"ku":case"lb":case"ml":case"mn":case"mr":case"nah":case"nb":case"ne":case"nl":case"nn":case"no":case"om":case"or":case"pa":case"pap":case"ps":case"pt":case"so":case"sq":case"sv":case"sw":case"ta":case"te":case"tk":case"ur":case"zu":return
count==1?0:1;case"am":case"bh":case"fil":case"fr":case"gun":case"hi":case"hy":case"ln":case"mg":case"nso":case"xbr":case"ti":case"wa":return
count==0||count==1?0:1;case"be":case"bs":case"hr":case"ru":case"sr":case"uk":return
count%10==1&&count%100!=11?0:count%10>=2&&count%10<=4&&(count%100<10||count%100>=20)?1:2;case"cs":case"sk":return
count==1?0:count>=2&&count<=4?1:2;case"ga":return
count==1?0:count==2?1:2;case"lt":return
count%10==1&&count%100!=11?0:count%10>=2&&(count%100<10||count%100>=20)?1:2;case"sl":return
count%100==1?0:count%100==2?1:count%100==3||count%100==4?2:3;case"mk":return
count%10==1?0:1;case"mt":return
count==1?0:count==0||count%100>1&&count%100<11?1:count%100>10&&count%100<20?2:3;case"lv":return
count==0?0:count%10==1&&count%100!=11?1:2;case"pl":return
count==1?0:count%10>=2&&count%10<=4&&(count%100<12||count%100>14)?1:2;case"cy":return
count==1?0:count==2?1:count==8||count==11?2:3;case"ro":return
count==1?0:count==0||count%100>0&&count%100<20?1:2;case"ar":return
count==0?0:count==1?1:count==2?2:count%100>=3&&count%100<=10?3:count%100>=11&&count%100<=99?4:5;default:return
0}};return Lang});

(function () {
    Lang.setMessages({"en.validation":{"accepted":"The :attribute must
be accepted.","active_url":"The :attribute is not a valid
URL.","after":"The :attribute must be a date after
:date.","alpha":"The :attribute may only contain
letters.","alpha_dash":"The :attribute may only contain letters,
numbers, and dashes.","alpha_num":"The :attribute may only contain
letters and numbers.","array":"The :attribute must be an
array.","before":"The :attribute must be a date before
:date.","between":{"numeric":"The :attribute must be between :min and
:max.","file":"The :attribute must be between :min and :max
kilobytes.","string":"The :attribute must be between :min and :max
characters.","array":"The :attribute must have between :min and :max
items."},"boolean":"The :attribute field must be true or
false.","confirmed":"The :attribute confirmation does not
match.","date":"The :attribute is not a valid
date.","date_format":"The :attribute does not match the format
:format.","different":"The :attribute and :other must be
different.","digits":"The :attribute must be :digits
digits.","digits_between":"The :attribute must be between :min and
:max digits.","dimensions":"The :attribute has invalid image
dimensions.","distinct":"The :attribute field has a duplicate
value.","email":"The :attribute must be a valid email
address.","exists":"The selected :attribute is invalid.","file":"The
:attribute must be a file.","filled":"The :attribute field is
required.","image":"The :attribute must be an image.","in":"The
selected :attribute is invalid.","in_array":"The :attribute field does
not exist in :other.","integer":"The :attribute must be an
integer.","ip":"The :attribute must be a valid IP
address.","json":"The :attribute must be a valid JSON
string.","max":{"numeric":"The :attribute may not be greater than
:max.","file":"The :attribute may not be greater than :max
kilobytes.","string":"The :attribute may not be greater than :max
characters.","array":"The :attribute may not have more than :max
items."},"mimes":"The :attribute must be a file of type:
:values.","min":{"numeric":"The :attribute must be at least
:min.","file":"The :attribute must be at least :min
kilobytes.","string":"The :attribute must be at least :min
characters.","array":"The :attribute must have at least :min
items."},"not_in":"The selected :attribute is invalid.","numeric":"The
:attribute must be a number.","present":"The :attribute field must be
present.","regex":"The :attribute format is invalid.","required":"The
:attribute field is required.","required_if":"The :attribute field is
required when :other is :value.","required_unless":"The :attribute
field is required unless :other is in :values.","required_with":"The
:attribute field is required when :values is
present.","required_with_all":"The :attribute field is required when
:values is present.","required_without":"The :attribute field is
required when :values is not present.","required_without_all":"The
:attribute field is required when none of :values are
present.","same":"The :attribute and :other must
match.","size":{"numeric":"The :attribute must be :size.","file":"The
:attribute must be :size kilobytes.","string":"The :attribute must be
:size characters.","array":"The :attribute must contain :size
items."},"string":"The :attribute must be a string.","timezone":"The
:attribute must be a valid zone.","unique":"The :attribute has already
been taken.","url":"The :attribute format is
invalid.","custom":{"attribute-name":{"rule-name":"custom-message"}},"attributes":[]},"en.passwords":{"password":"Passwords
must be at least six characters and match the
confirmation.","reset":"Your password has been reset!","sent":"We have
e-mailed your password reset link!","token":"This password reset token
is invalid.","user":"We can't find a user with that e-mail
address."},"en.auth":{"failed":"These credentials do not match our
records.","throttle":"Too many login attempts. Please try again in
:seconds seconds."},"en.pagination":{"previous":"&laquo;
Previous","next":"Next &raquo;"}});
})();

I cannot find the reason of the console error. Do you know what it is?

Thanks for your work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rmariuzzo/Laravel-JS-Localization/issues/57>, or mute
the thread

**Comment by rmariuzzo** [comment] 2016-08-27 17:35
Fixed with 5f57774b5381d2dcdf770d26aeb236069b05765c. Please, try again with:

```shell
composer require mariuzzo/laravel-js-localization
```

**Closed by rmariuzzo** 2016-08-27 17:35 UTC

**Comment by ksdev-pl** [comment] 2016-08-27 17:37
Works great, thank you very much!

**Comment by rmariuzzo** [comment] 2016-08-27 17:42
Thanks you @ksdev-pl! I appreciate your time and quick response!

**Comment by a-komarev** [comment] 2016-08-27 23:25
This was fast :+1:

**Comment by rmariuzzo** [comment] 2016-08-28 03:58
I hope to keep that pace.
